### ISSUE TITLE
Make a VPM version of the package to bundle with repositories ?

### ISSUE THREAD

**Issue by Spokeek** [anatawa12/vrc-get-resolver#5]
The way we add it is through a git url, should we make this package be able to be installed as a standard VPM package through ALCOM and VCC ?

**Comment by anatawa12** [comment]
I think providing vpm package resolver through vpm is not good since vpm is designed to gitignore packages provided through vpm. VRChat workarounds this problem by excluding resolver packages from gitignore but I think this is not good and I don't like embedding packages into the repository.

In addition, I think vpm package resolver is no longer working well with Safe Mode in Unity 2022. Missing package mostly leads compilation error. Therefore, I think we should use resolve features of vrc-get, ALCOM, vpm cli, or VCC and we should not depends on vpm package resolvers.
